name: compile

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Global Dependencies
        run: npm i -g minify terser
      - uses: actions/checkout@v3
      - name: Create url
        run: |
          touch index.html
          export MANGLE=`terser src/index.ai.js -c --module --mangle`
          perl -pe 's/{SCRIPT}/$ENV{MANGLE}/g' docs/index.base.html >> mangled.html
          minify mangled.html >> index.html
          zip -DXjq9 somesite.zip index.html
          rm -rf ./README.md
          touch ./README.md
          cat ./readme.base.md >> ./README.md
          echo "[game of pong](https://smolsite.zip/`cat somesite.zip | base64 --wrap 0`)"  >> ./README.md
      - name: Commit readme
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: "./README.md"
