name: compile

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Global Dependencies
        run: npm i -g minify
      - uses: actions/checkout@v3
      - name: Create url
        run: |
          touch index.min.html
          minify docs/index.html >> index.min.html
          zip -DXjq9 index.zip index.min.html
          rm -rf ./README.md
          touch ./README.md
          cat ./readme_preamble.md >> ./README.md
          A="[game of pong]("
          A+="https://smolsite.zip/`cat index.zip | base64 --wrap 0`"
          A+=")"
          cat A >> ./README.md
      - name: Commit readme
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: "./README.md"
