name: compile

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Global Dependencies
        run: npm i -g minify
      - name: Minify stuff
        run: touch ./docs/index.min.html && minify ./docs/index.html > ./docs/index.min.html
      - name: Zip stuff
        run: zip -DXjq9 index.zip ./docs/index.min.html
      - name: delete old
        run: rm -rf ./README.md
      - name: create new readme
        run: cat ./readme_preamble.md >> ./README.md && cat index.zip | base64 --wrap 0`" >> ./README.md && cat ")" >> ./README.md
      - name: Commit readme
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: "./README.md"
